version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
      - 10011:80
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
      - app

  app:
    build: .
    networks:
      - internal

  bot:
    build: bot
    environment:
      APPNAME: Admin
      APPURL: http://app:8080/
      APPURLREGEX: ^http://app:8080/.*
      APPFLAG: TCP1P{1n5p1R3d_by_l1V30v3rFloW_but_1_4dD3d_mor3_f1lt3rs_H4haH4h4}
      APPLIMIT: 2
      APPLIMITTIME: 60
    networks:
      - internal

networks:
  internal:
