version: '3'
services:
  talking:
    build:
      context: .
    working_dir: /home/usero
    container_name: talking
    restart: always
    ports:
      - "1965:1965"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
      - 1.0.0.1
